# Generated by Django 6.0.1 on 2026-02-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="p_phone",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
