# Generated by Django 6.0.1 on 2026-01-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_doctoravailability_doctorleave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="doc_image",
            field=models.ImageField(blank=True, null=True, upload_to="doctors"),
        ),
    ]
