# Generated by Django 6.0.2 on 2026-02-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0004_alter_doctors_doc_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctoravailability",
            options={
                "ordering": ["day"],
                "verbose_name_plural": "Doctor Availabilities",
            },
        ),
    ]
