# Generated by Django 4.2.28 on 2026-02-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0005_alter_doctoravailability_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="department_blogs"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to="doctors.departments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Blog",
                "verbose_name_plural": "Department Blogs",
                "ordering": ["-created_at"],
            },
        ),
    ]
