# Generated by Django 6.0.2 on 2026-02-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_adminrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminRequest",
        ),
    ]
